services:
  router:
    image: nginx:1.27.3
    container_name: ingress
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./ingress/nginx.conf:/etc/nginx/nginx.conf"
      - ~/certs/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - ~/certs/privkey.pem:/etc/nginx/ssl/privkey.pem
    depends_on:
      - client
      - server
      - coturn

  server:
    container_name: server
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    expose:
      - "9000"
    environment:
      - PORT=9000

#  server:
#    container_name: server
#    build:
#      context: .
#      dockerfile: docker/server-go.Dockerfile
#    expose:
#      - "9000"
#    environment:
#      - PORT=9000

  client:
    container_name: client
    build:
      context: .
      dockerfile: docker/client.Dockerfile
    expose:
      - "80"

  coturn:
    image: coturn/coturn
    container_name: coturn
    ports:
      - "3478:3478"
      - "5349:5349"
    volumes:
      - "~/certs:/etc/coturn/certs:ro"
    command:
      - --log-file=stdout
      - --lt-cred-mech
      - --realm=kondratevs.ru
      - --user=testuser:testpassword
      - --fingerprint
      - --external-ip=77.222.32.57
      - --listening-port=3478
      - --tls-listening-port=5349
