services:
  router:
    image: nginx:1.27.3
    container_name: ingress
    ports:
      - "80:80"
    volumes:
      - "./ingress/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - client
      - server

  server:
    container_name: server
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    expose:
      - "9000"
    environment:
      - PORT=9000

  client:
    container_name: client
    build:
      context: .
      dockerfile: docker/client.Dockerfile
    expose:
      - "80"
